## Usecase: Run multiple Printers on the same Host
##
## Assumptions:
## * I have two printers
## * One is called printer1, the other one printer2
## * printer1 is using serial port /dev/ttyUSB0 and webcam /dev/video0
## * printer2 is using serial port /dev/ttyUSB1 and webcam /dev/video1
##
## About this setup:
## * Moonraker services for each printer are available via their unique port (8101 and 8201 in this example).
## * Webcam services for each printer are available via their unique port (8102 and 8202 in this example)
## * Fluidd is used as Web frontend and is accessible via 80
## * You'll have to add your printers manually to fluidd via their moonraker ports eg. http://dockerhost:8101 and http://dockerhost:8201
##
## Setup:
## 1. Check out prind and enter the repository
##      > git clone https://github.com/mkuf/prind/
##      > cd prind
## 2. Create config files for each printer and set permissions
##      > for i in printer1 printer2; do cp config/printer.cfg config/${i}.cfg; cp config/moonraker.conf config/${i}.moonraker.conf; done
##      > chown -R 1000:1000 config
## 3. Copy this file to the root of the repository, overwriting the original docker-compose.yaml
##      > cp custom/docker-compose.custom.multiple-printers.yaml docker-compose.yaml
## 4. For each printer create a klipper, moonraker and webcam service as shown below
## 5. Make sure each service has a unique 'command' and is referencing the files created by 2.
## 6. Add your printers config to their corresponding file
## 7. Set the correct klippy_uds_address in the corresponding *.moonraker.conf
## 8. Update the Devices used for the webcam services
## 9. Start the stack
##      > docker compose up -d

## Common Templates
x-klipper-svc: &klipper-svc
  image: mkuf/klipper:latest
  restart: unless-stopped
  privileged: true
  group_add:
      - "20" # dialout group for serial port access
  volumes:
    - /dev:/dev
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs

x-moonraker-svc: &moonraker-svc
  image: mkuf/moonraker:latest
  restart: unless-stopped
  volumes:
    - /dev/null:/opt/klipper/config/null
    - /dev/null:/opt/klipper/docs/null
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs
    - /run/dbus:/run/dbus
    - /run/systemd:/run/systemd
    # - /dev/klipper:/dev/klipper # This is needed to access the klipper sockets created by the klipper services, make sure to set correct permissions on the host for /dev/klipper and its content (eg. via udev rules)

## Service Definitions
services:
  ## zwart
  ## Access api via port 8101/tcp
  zwart-klipper:
    <<: *klipper-svc
    command: >
      -I printer_data/run/zwart.klipper.tty
      -a printer_data/run/zwart.klipper.sock
      printer_data/config/zwart.cfg
      -l printer_data/logs/zwart.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: zwart
  zwart-moonraker:
    <<: *moonraker-svc
    command: >
      -d printer_data
      -c printer_data/config/zwart.moonraker.conf
      -l printer_data/logs/zwart.moonraker.log
    ports:
      - 8101:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: zwart

  ## wit
  ## Access api via port 8101/tcp
  wit-klipper:
    <<: *klipper-svc
    command: >
      -I printer_data/run/wit.klipper.tty
      -a printer_data/run/wit.klipper.sock
      printer_data/config/wit.cfg
      -l printer_data/logs/wit.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: wit
  wit-moonraker:
    <<: *moonraker-svc
    command: >
      -d printer_data
      -c printer_data/config/wit.moonraker.conf
      -l printer_data/logs/wit.moonraker.log
    ports:
      - 8201:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: wit

  ## paars
  ## Access api via port 8101/tcp
  paars-klipper:
    <<: *klipper-svc
    command: >
      -I printer_data/run/paars.klipper.tty
      -a printer_data/run/paars.klipper.sock
      printer_data/config/paars.cfg
      -l printer_data/logs/paars.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: paars
  paars-moonraker:
    <<: *moonraker-svc
    command: >
      -d printer_data
      -c printer_data/config/paars.moonraker.conf
      -l printer_data/logs/paars.moonraker.log
    ports:
      - 8301:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: paars

  ## blauw
  ## Access api via port 8101/tcp
  # blauw-klipper:
  #   <<: *klipper-svc
  #   command: >
  #     -I printer_data/run/blauw.klipper.tty
  #     -a printer_data/run/blauw.klipper.sock
  #     printer_data/config/blauw.cfg
  #     -l printer_data/logs/blauw.klippy.log
  #   labels:
  #     org.prind.service: klipper
  #     org.prind.printer: blauw
  # blauw-moonraker:
  #   <<: *moonraker-svc
  #   command: >
  #     -d printer_data
  #     -c printer_data/config/blauw.moonraker.conf
  #     -l printer_data/logs/blauw.moonraker.log
  #   ports:
  #     - 8401:7125
  #   labels:
  #     org.prind.service: moonraker
  #     org.prind.printer: blauw

  ## Use Fluidd as Frontend
  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    ports:
      - 80:80
    labels:
      org.prind.service: fluidd

volumes:
  run:
  gcode:
  log:
